name: Build and Release Chrome Extension

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install csscompressor jsmin

    - name: Package the Chrome extension
      run: python mentus_pack.py

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset to GitHub
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mentus-extension.zip
        asset_name: mentus-extension.zip
        asset_content_type: application/zip

    - name: Upload to Chrome Web Store
      uses: trmcnvn/chrome-addon@v2
      with:
        extension: mentus-extension.zip
        zip: true
        client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
